# Generated by Django 5.0.7 on 2024-08-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChechListItems',
            new_name='CheckListItems',
        ),
    ]
